name: WatchMemorialDay

on: issue_comment

jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && github.event.issue.title == 'MemorialDay' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Excute
        run: |
          python MemorialDay/main.py $ACTION $DATA
        env:
          ACTION: ${{ github.event.action }}
          DATA: ${{ github.event.comment.body }}
